#这里是配置文件，用来记录关键信息

app:
  name: CurrencyExchange
  port: :3000

database:
  dsn: root:root@tcp(127.0.0.1:3307)/fullstack?charset=utf8mb4&parseTime=True&loc=Local
  MaxIdleConns: 10
  MaxOpenConns: 100
